name: Hello World
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu_latest
    steps:
      - name: Build Step
        run: echo "A demo build"
  test:
    runs-on: ubuntu_latest
    steps:
      - name: Test Step
        run: echo "A demo Test"
  deploy:
    runs-on: ubuntu_latest
    steps:
      - name: Deploy Step
        run: echo "A demo Deploy"
